Making editor for movable (to chose function that is called in movementStep)
I tried to modify movementStep but something went wrong and it throws
TargetException: Object does not match target type when calling
method.Invoke(this, null) in Movable - movementStep. Although the right
method is chosen.